import { ArmorClass, BalanceConfig, DamageType, EnemyType, UpgradeType } from '../configs/balance-types';
import { ProjectileType } from '../projectiles/projectile-type.model';
import { WeaponType } from '../weapons/weapon.model';

export const defaultBalanceConfig: BalanceConfig = {
  economy: {
    startingMoney: 100,
    startingBaseHealth: 20,
    hoardPenaltyThresholdMultiplier: 1.5,
  },
  damageMultipliers: {
    [DamageType.Bullet]: {
      [ArmorClass.Light]: 1.2,
      [ArmorClass.Armored]: 0.7,
      [ArmorClass.Swarm]: 0.95,
      [ArmorClass.Shielded]: 0.8,
    },
    [DamageType.Explosive]: {
      [ArmorClass.Light]: 0.95,
      [ArmorClass.Armored]: 1.1,
      [ArmorClass.Swarm]: 1.35,
      [ArmorClass.Shielded]: 0.9,
    },
    [DamageType.Energy]: {
      [ArmorClass.Light]: 0.95,
      [ArmorClass.Armored]: 1.35,
      [ArmorClass.Swarm]: 0.9,
      [ArmorClass.Shielded]: 1.25,
    },
    [DamageType.SlowExplosive]: {
      [ArmorClass.Light]: 1,
      [ArmorClass.Armored]: 1.1,
      [ArmorClass.Swarm]: 1.15,
      [ArmorClass.Shielded]: 1,
    },
  },
  towers: [
    {
      type: WeaponType.BulletShooter,
      imageSrc: './assets/turrets/turret.png',
      cost: 20,
      projectileType: ProjectileType.Bullet,
      projectileSpeed: 250,
      upgrades: [
        {
          type: UpgradeType.Range,
          details: [
            { level: 1, cost: 6, value: 130 },
            { level: 2, cost: 10, value: 145 },
            { level: 3, cost: 15, value: 160 },
            { level: 4, cost: 22, value: 176 },
            { level: 5, cost: 30, value: 194 },
          ],
        },
        {
          type: UpgradeType.Damage,
          details: [
            { level: 1, cost: 6, value: 1.25 },
            { level: 2, cost: 10, value: 1.65 },
            { level: 3, cost: 14, value: 2.1 },
            { level: 4, cost: 19, value: 2.65 },
            { level: 5, cost: 25, value: 3.2 },
          ],
        },
        {
          type: UpgradeType.Speed,
          details: [
            { level: 1, cost: 7, value: 1450 },
            { level: 2, cost: 11, value: 1300 },
            { level: 3, cost: 16, value: 1175 },
            { level: 4, cost: 22, value: 1060 },
            { level: 5, cost: 29, value: 960 },
          ],
        },
      ],
    },
    {
      type: WeaponType.RocketLauncher,
      imageSrc: './assets/turrets/rocket-launcher-basic.png',
      cost: 48,
      projectileType: ProjectileType.Rocket,
      projectileSpeed: 125,
      upgrades: [
        {
          type: UpgradeType.Range,
          details: [
            { level: 1, cost: 10, value: 195 },
            { level: 2, cost: 16, value: 225 },
            { level: 3, cost: 24, value: 258 },
            { level: 4, cost: 35, value: 295 },
            { level: 5, cost: 48, value: 340 },
          ],
        },
        {
          type: UpgradeType.Damage,
          details: [
            { level: 1, cost: 12, value: 4.2 },
            { level: 2, cost: 19, value: 5.4 },
            { level: 3, cost: 28, value: 6.9 },
            { level: 4, cost: 40, value: 8.6 },
            { level: 5, cost: 54, value: 10.7 },
          ],
        },
        {
          type: UpgradeType.Speed,
          details: [
            { level: 1, cost: 11, value: 2050 },
            { level: 2, cost: 18, value: 1860 },
            { level: 3, cost: 27, value: 1680 },
            { level: 4, cost: 39, value: 1500 },
            { level: 5, cost: 52, value: 1330 },
          ],
        },
      ],
    },
    {
      type: WeaponType.LaserTurret,
      imageSrc: './assets/turrets/laser-shooter.png',
      cost: 88,
      projectileType: ProjectileType.Laser,
      projectileSpeed: null,
      upgrades: [
        {
          type: UpgradeType.Range,
          details: [
            { level: 1, cost: 14, value: 124 },
            { level: 2, cost: 22, value: 136 },
            { level: 3, cost: 32, value: 149 },
            { level: 4, cost: 45, value: 163 },
            { level: 5, cost: 60, value: 178 },
          ],
        },
        {
          type: UpgradeType.Damage,
          details: [
            { level: 1, cost: 18, value: 2.2 },
            { level: 2, cost: 28, value: 2.9 },
            { level: 3, cost: 40, value: 3.8 },
            { level: 4, cost: 55, value: 4.9 },
            { level: 5, cost: 72, value: 6.2 },
          ],
        },
        {
          type: UpgradeType.Speed,
          details: [
            { level: 1, cost: 19, value: 1650 },
            { level: 2, cost: 30, value: 1490 },
            { level: 3, cost: 43, value: 1345 },
            { level: 4, cost: 58, value: 1210 },
            { level: 5, cost: 76, value: 1080 },
          ],
        },
      ],
    },
    {
      type: WeaponType.NuclearLauncher,
      imageSrc: './assets/turrets/nuclear-turret.png',
      cost: 108,
      projectileType: ProjectileType.NuclearBullet,
      projectileSpeed: 500,
      upgrades: [
        {
          type: UpgradeType.Range,
          details: [
            { level: 1, cost: 16, value: 160 },
            { level: 2, cost: 25, value: 176 },
            { level: 3, cost: 36, value: 194 },
            { level: 4, cost: 50, value: 214 },
            { level: 5, cost: 66, value: 236 },
          ],
        },
        {
          type: UpgradeType.Damage,
          details: [
            { level: 1, cost: 20, value: 6.4 },
            { level: 2, cost: 31, value: 8.0 },
            { level: 3, cost: 45, value: 9.9 },
            { level: 4, cost: 62, value: 12.2 },
            { level: 5, cost: 82, value: 14.8 },
          ],
        },
        {
          type: UpgradeType.Speed,
          details: [
            { level: 1, cost: 22, value: 2550 },
            { level: 2, cost: 34, value: 2335 },
            { level: 3, cost: 49, value: 2130 },
            { level: 4, cost: 67, value: 1935 },
            { level: 5, cost: 88, value: 1750 },
          ],
        },
      ],
    },
    {
      type: WeaponType.SlowRocketLauncher,
      imageSrc: './assets/turrets/slow-turret.png',
      cost: 36,
      projectileType: ProjectileType.SlowRocket,
      projectileSpeed: 250,
      upgrades: [
        {
          type: UpgradeType.Range,
          details: [
            { level: 1, cost: 8, value: 205 },
            { level: 2, cost: 13, value: 232 },
            { level: 3, cost: 19, value: 262 },
            { level: 4, cost: 28, value: 295 },
            { level: 5, cost: 39, value: 332 },
          ],
        },
        {
          type: UpgradeType.Damage,
          details: [
            { level: 1, cost: 8, value: 1.55 },
            { level: 2, cost: 13, value: 1.95 },
            { level: 3, cost: 19, value: 2.45 },
            { level: 4, cost: 27, value: 3.05 },
            { level: 5, cost: 36, value: 3.8 },
          ],
        },
        {
          type: UpgradeType.Speed,
          details: [
            { level: 1, cost: 9, value: 1550 },
            { level: 2, cost: 14, value: 1400 },
            { level: 3, cost: 20, value: 1260 },
            { level: 4, cost: 29, value: 1135 },
            { level: 5, cost: 40, value: 1015 },
          ],
        },
      ],
    },
    {
      type: WeaponType.GrenadeThrower,
      imageSrc: './assets/turrets/grenade-thrower.png',
      cost: 30,
      projectileType: ProjectileType.GrenadeMine,
      projectileSpeed: null,
      upgrades: [
        {
          type: UpgradeType.Range,
          details: [
            { level: 1, cost: 7, value: 135 },
            { level: 2, cost: 11, value: 150 },
            { level: 3, cost: 16, value: 167 },
            { level: 4, cost: 23, value: 185 },
            { level: 5, cost: 31, value: 206 },
          ],
        },
        {
          type: UpgradeType.Damage,
          details: [
            { level: 1, cost: 9, value: 2.4 },
            { level: 2, cost: 14, value: 3.2 },
            { level: 3, cost: 21, value: 4.1 },
            { level: 4, cost: 30, value: 5.2 },
            { level: 5, cost: 41, value: 6.5 },
          ],
        },
        {
          type: UpgradeType.Speed,
          details: [
            { level: 1, cost: 9, value: 1820 },
            { level: 2, cost: 14, value: 1660 },
            { level: 3, cost: 21, value: 1515 },
            { level: 4, cost: 30, value: 1380 },
            { level: 5, cost: 40, value: 1260 },
          ],
        },
      ],
    },
  ],
  enemies: [
    {
      type: EnemyType.Basic,
      health: 10,
      speed: 145,
      reward: 10,
      imageName: 'BasicEnemy',
      armorClass: ArmorClass.Light,
      threat: 1,
      unlockWave: 1,
      weight: 1.35,
      baseDamageToBase: 1,
    },
    {
      type: EnemyType.FastAndWeak,
      health: 16,
      speed: 180,
      reward: 12,
      imageName: 'FastAndWeakEnemy',
      armorClass: ArmorClass.Swarm,
      threat: 1.25,
      unlockWave: 2,
      weight: 1.15,
      baseDamageToBase: 1,
    },
    {
      type: EnemyType.SlowAndStrong,
      health: 34,
      speed: 108,
      reward: 20,
      imageName: 'SlowAndStrongEnemy',
      armorClass: ArmorClass.Armored,
      threat: 2.25,
      unlockWave: 3,
      weight: 0.95,
      baseDamageToBase: 1,
    },
    {
      type: EnemyType.Boss,
      health: 48,
      speed: 92,
      reward: 28,
      imageName: 'BossEnemy',
      armorClass: ArmorClass.Shielded,
      threat: 3.25,
      unlockWave: 6,
      weight: 0.45,
      baseDamageToBase: 3,
    },
    {
      type: EnemyType.ScoutTank,
      health: 54,
      speed: 138,
      reward: 30,
      imageName: 'ScoutTankEnemy',
      armorClass: ArmorClass.Light,
      threat: 3.2,
      unlockWave: 5,
      weight: 0.8,
      baseDamageToBase: 2,
    },
    {
      type: EnemyType.SiegeTank,
      health: 70,
      speed: 90,
      reward: 38,
      imageName: 'SiegeTankEnemy',
      armorClass: ArmorClass.Armored,
      threat: 4.4,
      unlockWave: 7,
      weight: 0.6,
      baseDamageToBase: 2,
    },
    {
      type: EnemyType.LightHovercraft,
      health: 62,
      speed: 152,
      reward: 40,
      imageName: 'LightHovercraftEnemy',
      armorClass: ArmorClass.Swarm,
      threat: 4.3,
      unlockWave: 8,
      weight: 0.7,
      baseDamageToBase: 2,
    },
    {
      type: EnemyType.HeavyHovercraft,
      health: 88,
      speed: 106,
      reward: 48,
      imageName: 'HeavyHovercraftEnemy',
      armorClass: ArmorClass.Armored,
      threat: 5.7,
      unlockWave: 10,
      weight: 0.5,
      baseDamageToBase: 2,
    },
    {
      type: EnemyType.FighterPlane,
      health: 82,
      speed: 178,
      reward: 54,
      imageName: 'FighterPlaneEnemy',
      armorClass: ArmorClass.Swarm,
      threat: 6.2,
      unlockWave: 11,
      weight: 0.45,
      baseDamageToBase: 3,
    },
    {
      type: EnemyType.BomberPlane,
      health: 110,
      speed: 128,
      reward: 64,
      imageName: 'BomberPlaneEnemy',
      armorClass: ArmorClass.Shielded,
      threat: 8,
      unlockWave: 13,
      weight: 0.32,
      baseDamageToBase: 3,
    },
  ],
  waves: {
    intermissionMs: 10000,
    spawnIntervalMs: 1550,
    spawnIntervalDecayPerWave: 36,
    minSpawnIntervalMs: 420,
    budgetBase: 3.4,
    budgetGrowthLinear: 1.7,
    budgetGrowthPower: 1.25,
    budgetGrowthFactor: 0.74,
    eliteWeightBoostPerWave: 0.026,
    maxEnemiesPerWave: 55,
  },
};
