#!/usr/bin/env node
/* eslint-disable no-console */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = process.cwd();

function parseArg(args, name, fallback) {
  const idx = args.indexOf(name);
  if (idx === -1) {
    return fallback;
  }

  return args[idx + 1] ?? fallback;
}

function main() {
  const args = process.argv.slice(2);
  const inputPath = parseArg(args, '--input', path.join(ROOT, 'scripts', 'out', 'balance-config.json'));
  const outputPath = path.join(ROOT, 'src', 'app', 'models', 'configs', 'balance-runtime-config.generated.ts');

  if (!fs.existsSync(inputPath)) {
    throw new Error(`Input file not found: ${inputPath}`);
  }

  const raw = fs.readFileSync(inputPath, 'utf8');
  const parsed = JSON.parse(raw);
  if (!parsed || typeof parsed !== 'object' || !parsed.bestCandidate) {
    throw new Error('Invalid balance config: missing bestCandidate');
  }

  const candidate = parsed.bestCandidate;
  const generated = `// Auto-generated by npm run balance:apply\n` +
    `// Source: ${path.relative(ROOT, inputPath)}\n` +
    `export const generatedBalanceRuntimeConfig = ${JSON.stringify(candidate, null, 2)} as const;\n`;

  fs.writeFileSync(outputPath, generated, 'utf8');

  console.log(`Applied trained balance config to: ${path.relative(ROOT, outputPath)}`);
  if (parsed.objective) {
    console.log(`Best score: ${parsed.objective.bestScore}`);
    console.log(`Avg reached wave: ${parsed.objective.avgReachedWave}`);
    console.log(`Avg wallet: ${parsed.objective.avgWallet}`);
  }
}

main();
